In [1]:
import numpy as np
import pandas as pd
from mnist import MNIST

In [2]:
from mnist import MNIST

In [3]:
# Load whole mnist images from samples folder
mndata = MNIST('samples')

In [4]:
# read the training dataset of Minst
X_train, y_train = mndata.load_training()
# read the testing dataset
X_test, y_test = mndata.load_testing()

In [5]:
# read sample  training image
testimage = mndata.display(X_train[20]).split('\n')
print(y_train[20])
testimage

4


['',
 '............................',
 '............................',
 '............................',
 '............................',
 '............................',
 '..................@.........',
 '....@.............@@........',
 '....@@............@@........',
 '....@@@...........@@........',
 '....@@@..........@@@........',
 '.....@@@.........@@@........',
 '.....@@@@........@@@........',
 '......@@@........@@@........',
 '......@@@.....@@@@@@........',
 '.......@@@@@@@@@@@@@........',
 '.......@@@@@@@@@@@@@........',
 '.......@@@@@@@@..@@@........',
 '.......@@@@@.....@@@........',
 '.................@@@@.......',
 '.................@@@@.......',
 '.................@@@@.......',
 '..................@@@@......',
 '...................@@@......',
 '....................@.......',
 '............................',
 '............................',
 '............................',
 '............................']

In [6]:
# reshape the data and scale it
X_train = np.array(X_train)
X_test = np.array(X_test)

# Reshape the training and test dataset
# Reshape to include channel dimension (in this case, 1 channel)
X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28,28, 1)

In [7]:
X_test.shape

(10000, 28, 28, 1)

In [8]:
y_train = np.array(y_train)
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
y_test = np.array(y_test)
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
from tensorflow.keras.utils import to_categorical
y_train.shape

(60000,)

In [11]:
y_cat_test = to_categorical(y_test,10)
y_cat_train = to_categorical(y_train,10)

In [12]:
y_cat_train[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, MaxPooling2D

In [14]:
model = Sequential()

# CONVOLUTIONAL LAYER
#model.add(Conv2D(filters=32, kernel_size=(4,4),input_shape=(28, 28, 1), activation='relu',))
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))

# POOLING LAYER
model.add(MaxPool2D(pool_size=(2, 2)))

# FLATTEN IMAGES FROM 28 by 28 to 764 BEFORE FINAL LAYER
model.add(Flatten())

# 128 NEURONS IN DENSE HIDDEN LAYER (YOU CAN CHANGE THIS NUMBER OF NEURONS)
model.add(Dense(128, activation='relu'))

# LAST LAYER IS THE CLASSIFIER, THUS 10 POSSIBLE CLASSES
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#opt = SGD(lr=0.01, momentum=0.9)
#model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])


In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 5408)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               692352    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 693,962
Trainable params: 693,962
Non-trainable params: 0
_________________________________________________________________


In [16]:
y_cat_train.shape

(60000, 10)

In [17]:
from tensorflow.keras.callbacks import EarlyStopping

In [18]:
early_stop = EarlyStopping(monitor='val_loss',patience=2)

In [19]:
y_cat_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [20]:
#model.fit(x_train,y_cat_train,epochs=10,validation_data=(x_test,y_cat_test),callbacks=[early_stop])
#history = model.fit(trainX, trainY, epochs=10, batch_size=32, validation_data=(testX, testY), verbose=0)
history = model.fit(X_train, y_cat_train, epochs=10, batch_size=32, validation_data=(X_test, y_cat_test), verbose=1)

Epoch 1/10
1875/1875 [==============================] - 26s 13ms/step - loss: 10.5813 - accuracy: 0.6610 - val_loss: 1.0566 - val_accuracy: 0.6633
Epoch 2/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.9470 - accuracy: 0.7079 - val_loss: 1.1146 - val_accuracy: 0.7097
Epoch 3/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.7644 - accuracy: 0.7611 - val_loss: 0.4092 - val_accuracy: 0.9094
Epoch 4/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.3421 - accuracy: 0.9226 - val_loss: 0.2487 - val_accuracy: 0.9567
Epoch 5/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.2200 - accuracy: 0.9527 - val_loss: 0.2151 - val_accuracy: 0.9523
Epoch 6/10
1875/1875 [==============================] - 23s 13ms/step - loss: 0.1693 - accuracy: 0.9635 - val_loss: 0.1734 - val_accuracy: 0.9671
Epoch 7/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.1285 - accuracy: 0.9701 - val_loss: 0.1739 